### ISSUE TITLE
Cost calculation

### ISSUE THREAD

**Issue by cemo** [mhlabs/datahem#1]
Thanks for the project. It really opened new opportunities to us. Would you share some numbers about cost for us?

**Comment by ML-engineer** [comment]
Thanks. At MatHem we process almost a million (measurement protocol/Google Analytics) hits per day for less than 5 EUR/day.

**Comment by ML-engineer** [comment]
@cemo I hope that was the answer you were looking for. I will close this issue now.

**Comment by cemo** [comment]
Yes, thank you so much.

**Comment by ML-engineer** [comment]
Also, this week I will release a packaged version of datahem measurement protocol pipeline together with a tutorial/guide that makes it easy to set it up.
